import type { Product } from "./products";

/**
 * Hand-curated / scraped supplemental products that live alongside the
 * WordPress-synced catalog in products.ts. These are appended to PRODUCTS
 * at export time so re-running scripts/sync-wp-products.mjs never wipes
 * them out.
 *
 * Populated by scripts/sync-motoroil-cn.mjs (and any future per-category
 * scrapers pointed at flamingocarcare.com).
 */
export const EXTRA_PRODUCTS: Product[] = [
  {
    id: "flamingo-mineral-motor-oil-15w-40",
    code: "F4234SL",
    slug: "flamingo-mineral-motor-oil-15w-40",
    name: "Mineral Motor Oil 15W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 15W-40 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 15W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-10w-40",
    code: "F4224MA",
    slug: "flamingo-mineral-motor-oil-10w-40",
    name: "Mineral Motor Oil 10W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 10W-40 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 10W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-10w-30",
    code: "F4223SL",
    slug: "flamingo-mineral-motor-oil-10w-30",
    name: "Mineral Motor Oil 10W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 10W-30 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 10W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-synthetic-motor-oil-5w-40",
    code: "F4214B4",
    slug: "flamingo-synthetic-motor-oil-5w-40",
    name: "Synthetic Motor Oil 5W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo SYNTHETIC MOTOR OIL 5W-40 is a synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-30-c3",
    code: "F4313C3",
    slug: "flamingo-full-synthetic-motor-oil-5w-30-c3",
    name: "Full Synthetic Motor Oil 5W-30 C3",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-30 C3 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C3 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-30",
    code: "F4303G6",
    slug: "flamingo-full-synthetic-motor-oil-0w-30",
    name: "Full Synthetic Motor Oil 0W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-30-c3",
    code: "F4303C3",
    slug: "flamingo-full-synthetic-motor-oil-0w-30-c3",
    name: "Full Synthetic Motor Oil 0W-30 C3",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-30 C3 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C3 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-20-c5",
    code: "F4402C5",
    slug: "flamingo-full-synthetic-motor-oil-0w-20-c5",
    name: "Full Synthetic Motor Oil 0W-20 C5",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-20 C5 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-20 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C5 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  }
];
