import type { Product } from "./products";

/**
 * Hand-curated / scraped supplemental products that live alongside the
 * WordPress-synced catalog in products.ts. These are appended to PRODUCTS
 * at export time so re-running scripts/sync-wp-products.mjs never wipes
 * them out.
 *
 * Populated by scripts/sync-motoroil-cn.mjs (and any future per-category
 * scrapers pointed at flamingocarcare.com).
 */
export const EXTRA_PRODUCTS: Product[] = [
  {
    id: "flamingo-mineral-motor-oil-15w-40-f4234sl",
    code: "F4234SL",
    slug: "flamingo-mineral-motor-oil-15w-40-f4234sl",
    name: "Mineral Motor Oil 15W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 15W-40 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 15W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-20w-50-f4245sl",
    code: "F4245SL",
    slug: "flamingo-mineral-motor-oil-20w-50-f4245sl",
    name: "Mineral Motor Oil 20W-50",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 20W-50 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 20W-50 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-20w-50-f4245ma",
    code: "F4245MA",
    slug: "flamingo-mineral-motor-oil-20w-50-f4245ma",
    name: "Mineral Motor Oil 20W-50",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 20W-50 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 20W-50 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-10w-40-f4224ma",
    code: "F4224MA",
    slug: "flamingo-mineral-motor-oil-10w-40-f4224ma",
    name: "Mineral Motor Oil 10W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 10W-40 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 10W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-10w-40-f4224b4",
    code: "F4224B4",
    slug: "flamingo-mineral-motor-oil-10w-40-f4224b4",
    name: "Mineral Motor Oil 10W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 10W-40 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 10W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-10w-30-f4223sl",
    code: "F4223SL",
    slug: "flamingo-mineral-motor-oil-10w-30-f4223sl",
    name: "Mineral Motor Oil 10W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 10W-30 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 10W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-synthetic-motor-oil-10w-30-f4223b4",
    code: "F4223B4",
    slug: "flamingo-synthetic-motor-oil-10w-30-f4223b4",
    name: "Synthetic Motor Oil 10W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo SYNTHETIC MOTOR OIL 10W-30 is a synthetic motor oil engineered for consistent engine protection across a wide operating range. The 10W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-synthetic-motor-oil-5w-40-f4214b4",
    code: "F4214B4",
    slug: "flamingo-synthetic-motor-oil-5w-40-f4214b4",
    name: "Synthetic Motor Oil 5W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo SYNTHETIC MOTOR OIL 5W-40 is a synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-synthetic-motor-oil-5w-30-f4213g6",
    code: "F4213G6",
    slug: "flamingo-synthetic-motor-oil-5w-30-f4213g6",
    name: "Synthetic Motor Oil 5W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo SYNTHETIC MOTOR OIL 5W-30 is a synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-10w-30-f4323b4",
    code: "F4323B4",
    slug: "flamingo-full-synthetic-motor-oil-10w-30-f4323b4",
    name: "Full Synthetic Motor Oil 10W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 10W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 10W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-40-f4314b4",
    code: "F4314B4",
    slug: "flamingo-full-synthetic-motor-oil-5w-40-f4314b4",
    name: "Full Synthetic Motor Oil 5W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-40 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-30-c3-f4313c3",
    code: "F4313C3",
    slug: "flamingo-full-synthetic-motor-oil-5w-30-c3-f4313c3",
    name: "Full Synthetic Motor Oil 5W-30 C3",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-30 C3 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C3 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-30-f4313b4",
    code: "F4313B4",
    slug: "flamingo-full-synthetic-motor-oil-5w-30-f4313b4",
    name: "Full Synthetic Motor Oil 5W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-30-f4313g6",
    code: "F4313G6",
    slug: "flamingo-full-synthetic-motor-oil-5w-30-f4313g6",
    name: "Full Synthetic Motor Oil 5W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-30-f4303g6",
    code: "F4303G6",
    slug: "flamingo-full-synthetic-motor-oil-0w-30-f4303g6",
    name: "Full Synthetic Motor Oil 0W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-30-f4303a5",
    code: "F4303A5",
    slug: "flamingo-full-synthetic-motor-oil-0w-30-f4303a5",
    name: "Full Synthetic Motor Oil 0W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-30-c3-f4303c3",
    code: "F4303C3",
    slug: "flamingo-full-synthetic-motor-oil-0w-30-c3-f4303c3",
    name: "Full Synthetic Motor Oil 0W-30 C3",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-30 C3 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C3 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-20-f4302sp",
    code: "F4302SP",
    slug: "flamingo-full-synthetic-motor-oil-0w-20-f4302sp",
    name: "Full Synthetic Motor Oil 0W-20",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-20 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-20 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-40-f4404b4",
    code: "F4404B4",
    slug: "flamingo-full-synthetic-motor-oil-0w-40-f4404b4",
    name: "Full Synthetic Motor Oil 0W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-40 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-20-c5-f4402c5",
    code: "F4402C5",
    slug: "flamingo-full-synthetic-motor-oil-0w-20-c5-f4402c5",
    name: "Full Synthetic Motor Oil 0W-20 C5",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-20 C5 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-20 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C5 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-20-f4402vw",
    code: "F4402VW",
    slug: "flamingo-full-synthetic-motor-oil-0w-20-f4402vw",
    name: "Full Synthetic Motor Oil 0W-20",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-20 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-20 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-20-f1402vw",
    code: "F1402VW",
    slug: "flamingo-full-synthetic-motor-oil-0w-20-f1402vw",
    name: "Full Synthetic Motor Oil 0W-20",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-20 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-20 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-20-c5-f1402c5",
    code: "F1402C5",
    slug: "flamingo-full-synthetic-motor-oil-0w-20-c5-f1402c5",
    name: "Full Synthetic Motor Oil 0W-20 C5",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-20 C5 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-20 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C5 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-40-f1404b4",
    code: "F1404B4",
    slug: "flamingo-full-synthetic-motor-oil-0w-40-f1404b4",
    name: "Full Synthetic Motor Oil 0W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-40 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-20-f1302sp",
    code: "F1302SP",
    slug: "flamingo-full-synthetic-motor-oil-0w-20-f1302sp",
    name: "Full Synthetic Motor Oil 0W-20",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-20 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-20 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-30-c3-f1303c3",
    code: "F1303C3",
    slug: "flamingo-full-synthetic-motor-oil-0w-30-c3-f1303c3",
    name: "Full Synthetic Motor Oil 0W-30 C3",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-30 C3 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C3 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-30-f1303a5",
    code: "F1303A5",
    slug: "flamingo-full-synthetic-motor-oil-0w-30-f1303a5",
    name: "Full Synthetic Motor Oil 0W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-0w-30-f1303g6",
    code: "F1303G6",
    slug: "flamingo-full-synthetic-motor-oil-0w-30-f1303g6",
    name: "Full Synthetic Motor Oil 0W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 0W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 0W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-30-f1313g6",
    code: "F1313G6",
    slug: "flamingo-full-synthetic-motor-oil-5w-30-f1313g6",
    name: "Full Synthetic Motor Oil 5W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-30-f1313b4",
    code: "F1313B4",
    slug: "flamingo-full-synthetic-motor-oil-5w-30-f1313b4",
    name: "Full Synthetic Motor Oil 5W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-30-c3-f1313c3",
    code: "F1313C3",
    slug: "flamingo-full-synthetic-motor-oil-5w-30-c3-f1313c3",
    name: "Full Synthetic Motor Oil 5W-30 C3",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-30 C3 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. It meets the ACEA C3 specification for modern engines with after-treatment systems. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-5w-40-f1314b4",
    code: "F1314B4",
    slug: "flamingo-full-synthetic-motor-oil-5w-40-f1314b4",
    name: "Full Synthetic Motor Oil 5W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 5W-40 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-full-synthetic-motor-oil-10w-30-f1323b4",
    code: "F1323B4",
    slug: "flamingo-full-synthetic-motor-oil-10w-30-f1323b4",
    name: "Full Synthetic Motor Oil 10W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo full synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo FULL SYNTHETIC MOTOR OIL 10W-30 is a full synthetic motor oil engineered for consistent engine protection across a wide operating range. The 10W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-synthetic-motor-oil-5w-30-f1213g6",
    code: "F1213G6",
    slug: "flamingo-synthetic-motor-oil-5w-30-f1213g6",
    name: "Synthetic Motor Oil 5W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo SYNTHETIC MOTOR OIL 5W-30 is a synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-synthetic-motor-oil-5w-40-f1214b4",
    code: "F1214B4",
    slug: "flamingo-synthetic-motor-oil-5w-40-f1214b4",
    name: "Synthetic Motor Oil 5W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo SYNTHETIC MOTOR OIL 5W-40 is a synthetic motor oil engineered for consistent engine protection across a wide operating range. The 5W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-synthetic-motor-oil-10w-30-f1223b4",
    code: "F1223B4",
    slug: "flamingo-synthetic-motor-oil-10w-30-f1223b4",
    name: "Synthetic Motor Oil 10W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo synthetic motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo SYNTHETIC MOTOR OIL 10W-30 is a synthetic motor oil engineered for consistent engine protection across a wide operating range. The 10W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-10w-30-f1223sl",
    code: "F1223SL",
    slug: "flamingo-mineral-motor-oil-10w-30-f1223sl",
    name: "Mineral Motor Oil 10W-30",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 10W-30 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 10W-30 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-10w-40-f1224b4",
    code: "F1224B4",
    slug: "flamingo-mineral-motor-oil-10w-40-f1224b4",
    name: "Mineral Motor Oil 10W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 10W-40 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 10W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-10w-40-f1224ma",
    code: "F1224MA",
    slug: "flamingo-mineral-motor-oil-10w-40-f1224ma",
    name: "Mineral Motor Oil 10W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 10W-40 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 10W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-20w-50-f1245ma",
    code: "F1245MA",
    slug: "flamingo-mineral-motor-oil-20w-50-f1245ma",
    name: "Mineral Motor Oil 20W-50",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 20W-50 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 20W-50 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-20w-50-f1245sl",
    code: "F1245SL",
    slug: "flamingo-mineral-motor-oil-20w-50-f1245sl",
    name: "Mineral Motor Oil 20W-50",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 20W-50 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 20W-50 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  },
  {
    id: "flamingo-mineral-motor-oil-15w-40-f1234sl",
    code: "F1234SL",
    slug: "flamingo-mineral-motor-oil-15w-40-f1234sl",
    name: "Mineral Motor Oil 15W-40",
    category: "engine",
    realCategory: "Motor Oil",
    tagline: "Engine-grade chemistry.",
    shortBlurb: "Flamingo mineral motor oil — engineered for engine protection and longevity.",
    longCopy: "Flamingo MINERAL MOTOR OIL 15W-40 is a mineral motor oil engineered for consistent engine protection across a wide operating range. The 15W-40 viscosity profile delivers cold-start flow with high-temperature film strength, helping reduce wear, deposits, and oil consumption. Suitable for gasoline and diesel engines per the manufacturer's recommended grade.",
    features: [],
    application: [],
    cautions: [],
    specs: { volume: "" },
    heroColor: "#E50982",
    hero: false,
  }
];
