import manifest from "@/content/product-image-manifest.json";

const map = manifest as Record<string, string>;

/**
 * Resolve a product's downloaded image. The manifest is now keyed by
 * product slug (generated by scripts/sync-wp-products.mjs).
 */
export function getProductImage(slug: string): string | null {
  return map[slug] ?? null;
}

export function hasProductImage(slug: string): boolean {
  return slug in map;
}
